insert into public.companies (
  slug, name, description, url, category, tags, city, clicks, likes, created_at, initials, icon_bg, rank_score, status
) values
  ('clip', 'Clip', 'Terminales y pagos digitales para que cualquier negocio en México cobre con tarjeta, QR o link.', 'https://clip.mx', 'Fintech', ARRAY['pagos', 'POS', 'PyME']::text[], 'Ciudad de México', 18420, 942, '2012-05-10', 'CL', '#0f6b63', 98, 'approved'),
  ('bitso', 'Bitso', 'Exchange de criptomonedas para comprar, vender y transferir Bitcoin y otros activos desde México.', 'https://bitso.com', 'Fintech', ARRAY['crypto', 'exchange', 'web3']::text[], 'Ciudad de México', 22110, 1104, '2014-01-15', 'BI', '#00d4aa', 96, 'approved'),
  ('kavak', 'Kavak', 'Marketplace de autos seminuevos con inspección, financiamiento y entrega a domicilio.', 'https://kavak.com', 'Comercio', ARRAY['autos', 'marketplace', 'unicornio']::text[], 'Ciudad de México', 19880, 876, '2016-09-01', 'KA', '#111827', 94, 'approved'),
  ('konfio', 'Konfío', 'Crédito y software financiero para PyMEs mexicanas: préstamos, tarjetas y herramientas de gestión.', 'https://konfio.mx', 'Fintech', ARRAY['crédito', 'PyME', 'lending']::text[], 'Ciudad de México', 9120, 512, '2014-08-20', 'KO', '#2563eb', 88, 'approved'),
  ('clara', 'Clara', 'Tarjetas corporativas, control de gasto y cuentas por pagar para empresas en Latam.', 'https://www.clara.com', 'Fintech', ARRAY['gasto', 'corporativo', 'tarjetas']::text[], 'Ciudad de México', 13440, 701, '2019-03-12', 'CL', '#7c3aed', 91, 'approved'),
  ('nowports', 'Nowports', 'Forwarder digital para importar y exportar con tracking, documentos y cotizaciones en un solo lugar.', 'https://nowports.com', 'Logística', ARRAY['comercio exterior', 'freight', 'logística']::text[], 'Monterrey', 6230, 344, '2018-06-01', 'NP', '#0ea5e9', 82, 'approved'),
  ('justo', 'Jüsto', 'Supermercado online de productos frescos con entrega a domicilio y precios de mayoreo.', 'https://justo.mx', 'Comercio', ARRAY['retail', 'e-commerce', 'alimentos']::text[], 'Ciudad de México', 7880, 390, '2019-11-04', 'JÜ', '#16a34a', 80, 'approved'),
  ('belvo', 'Belvo', 'API de open finance para conectar cuentas bancarias, validar identidad y armar productos financieros.', 'https://belvo.com', 'Fintech', ARRAY['open banking', 'API', 'datos']::text[], 'Ciudad de México', 5410, 288, '2019-01-22', 'BE', '#4f46e5', 79, 'approved'),
  ('stori', 'Stori', 'Tarjeta de crédito digital para personas sin historial en buró, con app y educación financiera.', 'https://storicard.com', 'Fintech', ARRAY['crédito', 'inclusión', 'tarjeta']::text[], 'Ciudad de México', 10120, 455, '2018-04-18', 'ST', '#db2777', 85, 'approved'),
  ('incode', 'Incode', 'Plataforma de identidad digital con biometría, KYC y onboarding para bancos y fintechs.', 'https://incode.com', 'IA', ARRAY['identidad', 'biometría', 'KYC']::text[], 'Ciudad de México', 4320, 261, '2015-09-08', 'IN', '#1d4ed8', 77, 'approved'),
  ('wizeline', 'Wizeline', 'Estudio de producto e ingeniería que construye software, data e IA para empresas globales desde México.', 'https://www.wizeline.com', 'Servicios', ARRAY['software', 'producto', 'nearshore']::text[], 'Guadalajara', 3890, 210, '2014-02-01', 'WZ', '#ea580c', 74, 'approved'),
  ('softtek', 'Softtek', 'Consultora de transformación digital y servicios de TI con origen mexicano y operación global.', 'https://www.softtek.com', 'Servicios', ARRAY['consultoría', 'TI', 'enterprise']::text[], 'Monterrey', 5120, 198, '1982-01-01', 'SO', '#0369a1', 73, 'approved'),
  ('kueski', 'Kueski', 'Préstamos en línea y Kueski Pay, el pago diferido en comercios físicos y digitales de México.', 'https://kueski.com', 'Fintech', ARRAY['préstamos', 'BNPL', 'pagos']::text[], 'Guadalajara', 8670, 401, '2012-10-01', 'KU', '#059669', 84, 'approved'),
  ('aplazo', 'Aplazo', 'Compra ahora y paga después en e-commerce y tiendas, sin tarjeta de crédito.', 'https://aplazo.mx', 'Fintech', ARRAY['BNPL', 'retail', 'pagos']::text[], 'Ciudad de México', 6540, 312, '2020-02-14', 'AP', '#7c3aed', 78, 'approved'),
  ('minu', 'Minu', 'Anticipo de nómina y beneficios financieros para colaboradores, sin intereses abusivos.', 'https://minu.mx', 'Fintech', ARRAY['nómina', 'beneficios', 'HR']::text[], 'Ciudad de México', 2980, 176, '2019-07-09', 'MI', '#0f766e', 70, 'approved'),
  ('99minutos', '99minutos', 'Logística de última milla para e-commerce: entregas same-day, next-day y red de puntos pickup.', 'https://99minutos.com', 'Logística', ARRAY['última milla', 'e-commerce', 'envíos']::text[], 'Ciudad de México', 4210, 233, '2014-11-20', '99', '#f59e0b', 72, 'approved'),
  ('nuvocargo', 'Nuvocargo', 'Plataforma de freight forwarding México–Estados Unidos con tracking y aduana digital.', 'https://nuvocargo.com', 'Logística', ARRAY['freight', 'USA-México', 'aduana']::text[], 'Ciudad de México', 2760, 154, '2019-05-16', 'NU', '#0284c7', 68, 'approved'),
  ('conekta', 'Conekta', 'Pasarela de pagos para cobrar en línea con tarjeta, efectivo, transferencias y meses sin intereses.', 'https://conekta.com', 'Fintech', ARRAY['pagos', 'e-commerce', 'MSI']::text[], 'Ciudad de México', 7340, 329, '2012-03-01', 'CO', '#0d9488', 81, 'approved'),
  ('albo', 'albo', 'Cuenta digital y tarjeta para manejar tu dinero, transferencias SPEI y control de gastos desde la app.', 'https://albo.mx', 'Fintech', ARRAY['neobanco', 'cuenta', 'app']::text[], 'Ciudad de México', 5890, 267, '2016-04-11', 'AL', '#22c55e', 76, 'approved'),
  ('platzi', 'Platzi', 'Escuela online de tecnología, marketing y data con comunidad de estudiantes en todo México y Latam.', 'https://platzi.com', 'Otros', ARRAY['educación', 'cursos', 'comunidad']::text[], 'Ciudad de México', 15670, 980, '2011-08-01', 'PL', '#98ca3f', 90, 'approved'),
  ('improving', 'Improving', 'Desarrollo de software a la medida y equipos nearshore desde México para clientes en EUA y Canadá.', 'https://www.improving.com', 'Servicios', ARRAY['nearshore', 'software', 'equipos']::text[], 'Hermosillo', 2140, 121, '2002-01-01', 'IM', '#1e3a5f', 64, 'approved'),
  ('merama', 'Merama', 'Plataforma de e-commerce que invierte y escala marcas nativas digitales en marketplaces de Latam.', 'https://merama.io', 'Comercio', ARRAY['e-commerce', 'marcas', 'marketplaces']::text[], 'Ciudad de México', 1980, 98, '2020-08-01', 'ME', '#be185d', 63, 'approved'),
  ('doctoralia', 'Doctoralia', 'Directorio y agenda médica para encontrar especialistas, agendar citas y gestionar consultorios.', 'https://www.doctoralia.com.mx', 'Salud', ARRAY['salud', 'citas', 'médicos']::text[], 'Ciudad de México', 11240, 430, '2007-01-01', 'DO', '#00a3e0', 75, 'approved'),
  ('medu', 'MEDU', 'Plataforma de educación médica continua y comunidad para profesionales de la salud en México.', 'https://medu.mx', 'Salud', ARRAY['salud', 'educación', 'médicos']::text[], 'Ciudad de México', 1560, 87, '2018-09-01', 'MD', '#0e7490', 58, 'approved'),
  ('spin-by-oxxo', 'Spin by OXXO', 'Cuenta y pagos digitales de FEMSA para enviar dinero, pagar servicios y usar la red OXXO.', 'https://spinbyoxxo.com.mx', 'Fintech', ARRAY['pagos', 'cuenta', 'OXXO']::text[], 'Monterrey', 14320, 610, '2021-06-01', 'SP', '#e11d48', 87, 'approved'),
  ('didi-food', 'DiDi Food', 'App de delivery de comida y movilidad con operación fuerte en ciudades de todo México.', 'https://www.didi-food.com/es-MX', 'Comercio', ARRAY['delivery', 'comida', 'app']::text[], 'Ciudad de México', 16780, 540, '2018-01-01', 'DD', '#ff7a00', 83, 'approved'),
  ('unDosTres', 'unDosTres', 'Recargas, pago de servicios y marketplace de entretenimiento desde el celular, sin comisiones extra.', 'https://undostres.com.mx', 'Fintech', ARRAY['recargas', 'servicios', 'pagos']::text[], 'Ciudad de México', 3340, 142, '2013-05-01', 'UD', '#2563eb', 61, 'approved'),
  ('unico', 'Unico', 'Identidad digital y biometría para onboarding remoto, firmas y prevención de fraude.', 'https://unico.io', 'IA', ARRAY['identidad', 'fraude', 'IA']::text[], 'Ciudad de México', 1890, 104, '2018-02-01', 'UN', '#111827', 66, 'approved')
on conflict (slug) do nothing;

insert into public.events (
  slug, name, description, url, tags, city, venue, starts_at, ends_at, time, price, organizer, format
) values
  ('talent-land-2026', 'Talent Land 2026', 'La convención de talento tech más grande de Latam. Conferencias, hackathons, zona de reclutamiento y comunidad en Expo Guadalajara.', 'https://www.talent-land.mx', ARRAY['Presencial', 'IA', 'Talento']::text[], 'Guadalajara', 'Expo Guadalajara', '2026-09-15', '2026-09-18', '09:00 hs', 'De pago', 'Talent Network', 'Presencial'),
  ('ai-summit-mexico-2026', 'AI Summit México 2026', 'Cumbre de inteligencia artificial aplicada a negocio, producto y gobierno. Charlas, demos y networking en Reforma.', 'https://aisummit.mx', ARRAY['Presencial', 'IA']::text[], 'Ciudad de México', 'Centro Citibanamex', '2026-09-08', null, '08:30 hs', 'De pago', 'AI México', 'Presencial'),
  ('devfest-cdmx-2026', 'DevFest CDMX 2026', 'Conferencia comunitaria de Google Developer Groups: Android, Cloud, Firebase, Flutter y Gemini, con tracks en español.', 'https://gdg.community.dev', ARRAY['Presencial', 'Mobile', 'Cloud']::text[], 'Ciudad de México', 'Campus Google for Startups', '2026-10-03', null, '09:00 hs', 'Gratis', 'GDG Ciudad de México', 'Presencial'),
  ('jalisco-tech-week-2026', 'Jalisco Tech Week 2026', 'Semana de startups, inversionistas y talento en el Silicon Valley mexicano. Pitches, meetups y open offices.', 'https://jalisco.tech', ARRAY['Presencial', 'Startups']::text[], 'Guadalajara', 'Andares / Distrito Tech', '2026-09-22', '2026-09-26', '10:00 hs', 'Gratis', 'IJALTI / Gobierno de Jalisco', 'Presencial'),
  ('hackathon-fintech-mty', 'Hackathon Fintech Monterrey', '48 horas para construir productos de pagos, crédito e inclusión financiera con APIs de bancos y fintechs locales.', 'https://hackathon.fintech.mx', ARRAY['Presencial', 'Fintech', 'Hackathon']::text[], 'Monterrey', 'Distrito Tec', '2026-09-12', '2026-09-13', '09:00 hs', 'Gratis', 'Fintech México / Tec de Monterrey', 'Presencial'),
  ('women-who-code-cdmx', 'Women Who Code México · Meetup', 'Encuentro mensual de ingeniería: charlas de carrera, sistema de diseño y un AMA con engineering managers.', 'https://www.womenwhocode.com', ARRAY['Presencial', 'Comunidad']::text[], 'Ciudad de México', 'WeWork Reforma 265', '2026-09-04', null, '19:00 hs', 'Gratis', 'Women Who Code México', 'Presencial'),
  ('pycon-mexico-2026', 'PyCon México 2026', 'Conferencia nacional de Python: data, backend, ciencia y comunidad. Talleres el primer día, talks el resto.', 'https://mx.pycon.org', ARRAY['Presencial', 'Python']::text[], 'Puebla', 'Complejo Cultural Universitario BUAP', '2026-10-17', '2026-10-19', '09:00 hs', 'De pago', 'Python México', 'Presencial'),
  ('react-cdmx-septiembre', 'React CDMX · Septiembre', 'Meetup de React y Next.js: Server Components, caching y una demo en vivo de un design system.', 'https://www.meetup.com', ARRAY['Presencial', 'Frontend']::text[], 'Ciudad de México', 'Platzi HQ', '2026-09-10', null, '19:00 hs', 'Gratis', 'React México', 'Presencial'),
  ('startup-weekend-cdmx', 'Startup Weekend CDMX', '54 horas para validar una idea, armar equipo y presentar frente a inversionistas. Abierto a builders de cualquier perfil.', 'https://startupweekend.org', ARRAY['Presencial', 'Startups']::text[], 'Ciudad de México', 'Universidad Anáhuac', '2026-08-21', '2026-08-23', '18:00 hs', 'De pago', 'Techstars / Startup Weekend', 'Presencial'),
  ('campus-party-mexico-2026', 'Campus Party México 2026', 'Festival de innovación, gaming y tecnología con campamento, workshops y escenarios 24/7.', 'https://mexico.campus-party.org', ARRAY['Presencial', 'Comunidad']::text[], 'Puebla', 'Centro Expositor Puebla', '2026-08-14', '2026-08-17', '10:00 hs', 'De pago', 'Campus Party', 'Presencial'),
  ('cybersec-meetup-gdl', 'CyberSec Meetup GDL', 'Charlas de appsec, cloud security y un CTF relámpago. Abierto y sin costo para la comunidad de Jalisco.', 'https://owasp.org', ARRAY['Presencial', 'Seguridad']::text[], 'Guadalajara', 'HackerGarage', '2026-08-20', null, '18:30 hs', 'Gratis', 'OWASP Guadalajara', 'Presencial')
on conflict (slug) do nothing;
