-- Directory starts empty. New projects arrive via /publicar → submissions.

insert into public.events (
  slug, name, description, url, tags, city, venue, starts_at, ends_at, time, price, organizer, format
) values
  ('talent-land-2026', 'Talent Land 2026', 'La convención de talento tech más grande de Latam. Conferencias, hackathons, zona de reclutamiento y comunidad en Expo Guadalajara.', 'https://www.talent-land.mx', ARRAY['Presencial', 'IA', 'Talento']::text[], 'Guadalajara', 'Expo Guadalajara', '2026-09-15', '2026-09-18', '09:00 hs', 'De pago', 'Talent Network', 'Presencial'),
  ('ai-summit-mexico-2026', 'AI Summit México 2026', 'Cumbre de inteligencia artificial aplicada a negocio, producto y gobierno. Charlas, demos y networking en Reforma.', 'https://aisummit.mx', ARRAY['Presencial', 'IA']::text[], 'Ciudad de México', 'Centro Citibanamex', '2026-09-08', null, '08:30 hs', 'De pago', 'AI México', 'Presencial'),
  ('devfest-cdmx-2026', 'DevFest CDMX 2026', 'Conferencia comunitaria de Google Developer Groups: Android, Cloud, Firebase, Flutter y Gemini, con tracks en español.', 'https://gdg.community.dev', ARRAY['Presencial', 'Mobile', 'Cloud']::text[], 'Ciudad de México', 'Campus Google for Startups', '2026-10-03', null, '09:00 hs', 'Gratis', 'GDG Ciudad de México', 'Presencial'),
  ('jalisco-tech-week-2026', 'Jalisco Tech Week 2026', 'Semana de startups, inversionistas y talento en el Silicon Valley mexicano. Pitches, meetups y open offices.', 'https://jalisco.tech', ARRAY['Presencial', 'Startups']::text[], 'Guadalajara', 'Andares / Distrito Tech', '2026-09-22', '2026-09-26', '10:00 hs', 'Gratis', 'IJALTI / Gobierno de Jalisco', 'Presencial'),
  ('hackathon-fintech-mty', 'Hackathon Fintech Monterrey', '48 horas para construir productos de pagos, crédito e inclusión financiera con APIs de bancos y fintechs locales.', 'https://hackathon.fintech.mx', ARRAY['Presencial', 'Fintech', 'Hackathon']::text[], 'Monterrey', 'Distrito Tec', '2026-09-12', '2026-09-13', '09:00 hs', 'Gratis', 'Fintech México / Tec de Monterrey', 'Presencial'),
  ('women-who-code-cdmx', 'Women Who Code México · Meetup', 'Encuentro mensual de ingeniería: charlas de carrera, sistema de diseño y un AMA con engineering managers.', 'https://www.womenwhocode.com', ARRAY['Presencial', 'Comunidad']::text[], 'Ciudad de México', 'WeWork Reforma 265', '2026-09-04', null, '19:00 hs', 'Gratis', 'Women Who Code México', 'Presencial'),
  ('pycon-mexico-2026', 'PyCon México 2026', 'Conferencia nacional de Python: data, backend, ciencia y comunidad. Talleres el primer día, talks el resto.', 'https://mx.pycon.org', ARRAY['Presencial', 'Python']::text[], 'Puebla', 'Complejo Cultural Universitario BUAP', '2026-10-17', '2026-10-19', '09:00 hs', 'De pago', 'Python México', 'Presencial'),
  ('react-cdmx-septiembre', 'React CDMX · Septiembre', 'Meetup de React y Next.js: Server Components, caching y una demo en vivo de un design system.', 'https://www.meetup.com', ARRAY['Presencial', 'Frontend']::text[], 'Ciudad de México', 'Platzi HQ', '2026-09-10', null, '19:00 hs', 'Gratis', 'React México', 'Presencial'),
  ('startup-weekend-cdmx', 'Startup Weekend CDMX', '54 horas para validar una idea, armar equipo y presentar frente a inversionistas. Abierto a builders de cualquier perfil.', 'https://startupweekend.org', ARRAY['Presencial', 'Startups']::text[], 'Ciudad de México', 'Universidad Anáhuac', '2026-08-21', '2026-08-23', '18:00 hs', 'De pago', 'Techstars / Startup Weekend', 'Presencial'),
  ('campus-party-mexico-2026', 'Campus Party México 2026', 'Festival de innovación, gaming y tecnología con campamento, workshops y escenarios 24/7.', 'https://mexico.campus-party.org', ARRAY['Presencial', 'Comunidad']::text[], 'Puebla', 'Centro Expositor Puebla', '2026-08-14', '2026-08-17', '10:00 hs', 'De pago', 'Campus Party', 'Presencial'),
  ('cybersec-meetup-gdl', 'CyberSec Meetup GDL', 'Charlas de appsec, cloud security y un CTF relámpago. Abierto y sin costo para la comunidad de Jalisco.', 'https://owasp.org', ARRAY['Presencial', 'Seguridad']::text[], 'Guadalajara', 'HackerGarage', '2026-08-20', null, '18:30 hs', 'Gratis', 'OWASP Guadalajara', 'Presencial')
on conflict (slug) do nothing;
